name: Frontend CI

on:
  push:
    branches: [ main ]
    paths:
      -  'frontend/**'

  pull_request:
    branches: [ main ]
    paths:
      -  'frontend/**'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'false'
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock

      - name: Install
        working-directory: frontend/
        run: yarn install

      - name: Build
        working-directory: frontend/
        run: yarn build
      - name: Lint
        working-directory: frontend/
        run: yarn lint

      - name: Unit Tests
        working-directory: frontend/
        run: yarn test:unit
